# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=20, verbose_name='module name')),
                ('module_caption', models.CharField(max_length=255, verbose_name='module caption')),
                ('models_extend', models.CharField(max_length=2000, verbose_name='module extend')),
            ],
        ),
        migrations.CreateModel(
            name='Server_app_categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_categ_name', models.CharField(max_length=30, verbose_name='name of service application category ')),
            ],
        ),
        migrations.CreateModel(
            name='Server_fun_categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_categ_name', models.CharField(max_length=20, verbose_name='name of service function category ')),
            ],
        ),
        migrations.CreateModel(
            name='Server_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=13, verbose_name='server name')),
                ('server_wip', models.CharField(max_length=15, verbose_name='server public network ip')),
                ('server_lip', models.CharField(max_length=12, verbose_name='server inner network ip')),
                ('server_op', models.CharField(max_length=10, verbose_name='OS of server')),
                ('server_app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.Server_app_categ', verbose_name='id of service application category')),
            ],
        ),
        migrations.AddField(
            model_name='server_app_categ',
            name='server_categ_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.Server_fun_categ', verbose_name='foreign key,service function id,delete cascade '),
        ),
    ]
