# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server_app_categ',
            old_name='server_categ_id',
            new_name='server_fun_categ',
        ),
        migrations.RenameField(
            model_name='server_list',
            old_name='server_app_id',
            new_name='server_app_categ',
        ),
    ]
