# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0004_auto_20170802_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.IntegerField(help_text='history id', max_length=11)),
                ('history_user', models.CharField(help_text='history user', max_length=15)),
                ('history_datetime', models.DateTimeField(help_text='happen date')),
                ('db_datetime', models.DateTimeField(help_text='insert into db date')),
                ('history_command', models.CharField(help_text='history command', max_length=255)),
                ('server_list', models.ForeignKey(help_text='history of the server', on_delete=django.db.models.deletion.CASCADE, to='oms.Server_list')),
            ],
        ),
        migrations.AlterField(
            model_name='module_list',
            name='module_extend',
            field=models.TextField(help_text='module extend'),
        ),
    ]
