# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0007_oms_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oms_user',
            name='user_last_modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='user last modify time'),
        ),
        migrations.AlterField(
            model_name='module_list',
            name='module_caption',
            field=models.CharField(max_length=255, verbose_name='module caption'),
        ),
        migrations.AlterField(
            model_name='module_list',
            name='module_extend',
            field=models.TextField(verbose_name='module extend'),
        ),
        migrations.AlterField(
            model_name='module_list',
            name='module_name',
            field=models.CharField(max_length=20, verbose_name='module name'),
        ),
        migrations.AlterField(
            model_name='oms_user',
            name='user_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='user create time'),
        ),
        migrations.AlterField(
            model_name='oms_user',
            name='user_email',
            field=models.CharField(max_length=30, verbose_name='user email'),
        ),
        migrations.AlterField(
            model_name='oms_user',
            name='user_name',
            field=models.CharField(max_length=11, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='oms_user',
            name='user_password',
            field=models.CharField(max_length=15, verbose_name='user password'),
        ),
        migrations.AlterField(
            model_name='server_app_categ',
            name='app_categ_name',
            field=models.CharField(max_length=30, verbose_name='name of service application category '),
        ),
        migrations.AlterField(
            model_name='server_app_categ',
            name='server_fun_categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.Server_fun_categ', verbose_name='foreign key,service function id,delete cascade '),
        ),
        migrations.AlterField(
            model_name='server_fun_categ',
            name='server_categ_name',
            field=models.CharField(max_length=20, verbose_name='name of service function category '),
        ),
        migrations.AlterField(
            model_name='server_history',
            name='db_datetime',
            field=models.DateTimeField(verbose_name='insert into db date'),
        ),
        migrations.AlterField(
            model_name='server_history',
            name='history_command',
            field=models.CharField(max_length=255, verbose_name='history command'),
        ),
        migrations.AlterField(
            model_name='server_history',
            name='history_datetime',
            field=models.DateTimeField(verbose_name='happen date'),
        ),
        migrations.AlterField(
            model_name='server_history',
            name='history_id',
            field=models.IntegerField(verbose_name='history id'),
        ),
        migrations.AlterField(
            model_name='server_history',
            name='history_user',
            field=models.CharField(max_length=15, verbose_name='history user'),
        ),
        migrations.AlterField(
            model_name='server_history',
            name='server_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.Server_list', verbose_name='history of the server'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='server_app_categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.Server_app_categ', verbose_name='id of service application category'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='server_lip',
            field=models.CharField(max_length=12, verbose_name='server inner network ip'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='server_name',
            field=models.CharField(max_length=13, verbose_name='server name'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='server_op',
            field=models.CharField(max_length=10, verbose_name='OS of server'),
        ),
        migrations.AlterField(
            model_name='server_list',
            name='server_wip',
            field=models.CharField(max_length=15, verbose_name='server public network ip'),
        ),
    ]
